import { useEffect, useRef, useState, type ReactNode } from "react";
import { ArrowClockwise, ArrowRight, GitBranch, Headset, Phone, Plus, Trash, Users, Voicemail, CheckCircle } from "@phosphor-icons/react";
import { queueConfigSchema, type AdminSnapshot, type AdminLine, type CenterSnapshot, type VoiceDestination, type VoiceFlow, type VoiceFlowRecord, type VoiceQueue, type QueueConfig, type CenterAgent, type CenterTask } from "@onoff/contracts";
import { Avatar, EmptyState, Modal } from "./ui";
import { formatPhone } from "./conversation-model";
import "./admin.css";
import "./call-center.css";
import { FlowEditor } from "./IvrBuilder";

type Api = <T>(path: string, init?: RequestInit) => Promise<T>;
type Props = { organizationId: string; api: Api; audio(path:string):Promise<Blob>; refreshKey?: number };
const errorText = (e:unknown) => e instanceof Error ? e.message : "Une erreur est survenue.";
const duration = (seconds:number) => `${Math.floor(seconds/60)} min ${Math.floor(seconds%60).toString().padStart(2,"0")}`;
const labels:Record<string,string> = {pending:"En attente",reserved:"Sonnerie",assigned:"En conversation",wrapping:"Fin d’appel"};
const queueDefaults = ():QueueConfig => ({name:"Accueil",memberIds:[],maxWaitSeconds:120,ringTimeout:25,holdMessage:"Tous nos conseillers sont occupés. Nous allons prendre votre appel.",holdMusicUrl:null,announcePosition:true,overflow:{type:"voicemail"}});
const unpublishedChanges = (flow:VoiceFlowRecord) => !flow.published || JSON.stringify({...flow.draft,enabled:true})!==JSON.stringify({...flow.published,enabled:true});

export function CallCenter({organizationId,api,audio,refreshKey=0}:Props){
  const [data,setData]=useState<CenterSnapshot|null>(null),[admin,setAdmin]=useState<AdminSnapshot|null>(null);
  const [tab,setTab]=useState("flows"),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
  const [wizard,setWizard]=useState(false),[flowLine,setFlowLine]=useState<AdminLine|null>(null),[queueEditor,setQueueEditor]=useState<VoiceQueue|"new"|null>(null),[agentEditor,setAgentEditor]=useState<CenterAgent|null>(null),[transfer,setTransfer]=useState<CenterTask|null>(null);
  const apiRef=useRef(api);apiRef.current=api;
  const generation=useRef(0);
  const base=`/v1/organizations/${organizationId}/center`;
  async function reload(){
    const gen=++generation.current;
    try{const [snapshot,access]=await Promise.all([apiRef.current<CenterSnapshot>(base),apiRef.current<AdminSnapshot>(`/v1/organizations/${organizationId}/admin`)]);if(gen===generation.current){setData(snapshot);setAdmin(access);setError("");}}
    catch(e){if(gen===generation.current){setError(errorText(e));setData(d=>d?{...d,live:false,tasks:[],statistics:[],agents:d.agents.map(a=>({...a,activity:"Indisponible",available:false}))}:null);}}

  }
  useEffect(()=>{void reload();const timer=window.setInterval(()=>{if(document.visibilityState==="visible")void reload();},10000);const refresh=()=>void reload();window.addEventListener("focus",refresh);return()=>{generation.current++;clearInterval(timer);window.removeEventListener("focus",refresh);};},[organizationId,refreshKey]);
  async function act(work:()=>Promise<unknown>,message:string){setBusy(true);setError("");try{await work();setNotice(message);await reload();}catch(e){setError(errorText(e));await reload();setError(errorText(e));}finally{setBusy(false);}}
  async function saved(message:string){setWizard(false);setFlowLine(null);setQueueEditor(null);setAgentEditor(null);setTransfer(null);setNotice(message);await reload();}
  async function toggleIvr(line:AdminLine,flow:VoiceFlowRecord|undefined){
    const published=flow?.published;
    const advancedActive=!!published?.enabled;
    const simpleActive=!advancedActive&&line.ivr_config.enabled;
    if(published&&!simpleActive) await act(()=>api(`${base}/flows/${line.id}/activation`,{method:"PATCH",body:JSON.stringify({enabled:!advancedActive,version:flow.version})}),advancedActive?"IVR désactivé. Les nouveaux appels sonnent directement sur le numéro.":"IVR activé pour les nouveaux appels.");
    else await act(()=>api(`/v1/organizations/${organizationId}/admin/lines/${line.id}/ivr`,{method:"PUT",body:JSON.stringify({config:{...line.ivr_config,enabled:!simpleActive},version:line.updated_at})}),simpleActive?"Menu vocal désactivé. Les nouveaux appels sonnent directement sur le numéro.":"Menu vocal activé pour les nouveaux appels.");
  }
  const voiceLines=admin?.lines.filter(l=>l.status==="active"&&l.voice_enabled)??[];
  const stats=data?.statistics??[];
  return <section className="admin-page center-page">
    <div className="admin-intro"><div><h2>Accueil téléphonique</h2></div><div className="center-actions"><button className="button button-secondary" onClick={()=>void reload()}><ArrowClockwise size={16}/>Actualiser</button><button className="button button-primary" disabled={!voiceLines.length||busy||!data?.configured} onClick={()=>{if(voiceLines.length===1)setFlowLine(voiceLines[0]!);else setWizard(true);}}><Plus size={17}/>Configurer un numéro</button></div></div>
    {notice&&<p className="admin-notice" role="status"><CheckCircle size={17}/>{notice}</p>}
    {error&&<p className="admin-error" role="alert">{error}</p>}
    {!data&&!error&&<p className="admin-loading">Connexion au centre d’appels…</p>}
    {data&&<>
      <div className="center-health"><span className={`center-live ${data.live?"connected":""}`}><i/>{data.live?"Twilio connecté":data.configured?"Twilio à initialiser":"Voix non configurée"}</span><span>{data.live?`Actualisé à ${new Date(data.fetchedAt).toLocaleTimeString("fr-FR")} · toutes les 10 s`:data.liveError??"Activez le centre pour créer les files et gérer vos agents."}</span>{data.configured&&!data.provisioned&&<button disabled={busy} className="text-button" onClick={()=>void act(()=>api(`${base}/setup`,{method:"POST"}),"Le centre d’appels Twilio est prêt.")}>Activer le centre d’appels <ArrowRight/></button>}</div>
      {data.liveError&&<p className="admin-error" role="alert">{data.liveError}</p>}
      {tab!=="flows"&&<div className="center-metrics">{[["En attente",data.live?stats.reduce((n,s)=>n+s.waiting,0):"—"],["En conversation",data.live?stats.reduce((n,s)=>n+s.assigned,0):"—"],["Agents disponibles",data.live?data.agents.filter(a=>a.available&&a.reachable).length:"—"],["Attente la plus longue",data.live?duration(Math.max(0,...stats.map(s=>s.longestWait))):"—"]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>}
      <nav className="section-tabs" aria-label="Centre d’appels">{[["flows","Menus vocaux",<GitBranch key="i"/>],["queues","Files d’attente",<Headset key="i"/>],["agents","Agents",<Users key="i"/>],["calls","Appels en direct",<Phone key="i"/>],["voicemail","Messages vocaux",<Voicemail key="i"/>]].map(([id,label,icon])=><button key={String(id)} className={tab===id?"active":""} onClick={()=>setTab(String(id))}>{icon}{label}</button>)}</nav>
      {tab==="flows"&&<><div className="center-flow-intro"><div><h3>Un accueil par numéro</h3><p>Menu désactivé : sonnerie directe. Les changements concernent les nouveaux appels.</p></div></div><div className="center-flows">{voiceLines.map(line=>{const flow=data.flows.find(f=>f.line_id===line.id);const published=flow?.published;const advancedActive=!!published?.enabled;const simpleActive=!advancedActive&&line.ivr_config.enabled;const simpleMenu=line.ivr_config.options.length>0;const enabled=advancedActive||simpleActive;const canToggle=!!published||simpleMenu;const hasDraft=!!flow&&unpublishedChanges(flow);const route=advancedActive?(published?.entry.type==="number"?"Renvoi vers un numéro":published?.entry.type==="queue"?"File d’attente":published?.entry.type==="menu"?`${published.menus.length} menu${published.menus.length>1?"s":""} vocal${published.menus.length>1?"aux":""}`:"Accueil vocal"):simpleActive?`${line.ivr_config.options.length} choix par touche`:"Sonnerie directe";return <article className="center-flow-card" key={line.id}><div className="center-card-heading"><span className="admin-line-icon"><GitBranch size={23}/></span><span className={`admin-status ${enabled?"active":""}`}>{enabled?"IVR activé":canToggle?"IVR désactivé":"À configurer"}</span></div><h3>{advancedActive?published?.name:simpleActive?"Menu vocal simple":published?.name??flow?.draft.name??"Accueil téléphonique"}</h3><p>{formatPhone(line.phone_number)}</p><div className="center-route"><span><Phone/>Appel entrant</span><ArrowRight/><span>{route}</span></div><div className="center-flow-control"><span><b>Menu vocal</b><small>{enabled?"En service sur ce numéro":canToggle?"Les appels arrivent directement":"Publiez un parcours pour l’activer"}</small></span><button type="button" role="switch" aria-checked={enabled} aria-label={`${enabled?"Désactiver":"Activer"} le menu vocal du ${formatPhone(line.phone_number)}`} className={`center-switch${enabled?" is-on":""}`} disabled={busy||!canToggle} onClick={()=>void toggleIvr(line,flow)}><span/></button></div>{hasDraft&&<p className="center-draft-note">{published?"Modifications non publiées : le menu en service reste inchangé.":"Brouillon enregistré : publiez-le pour mettre le menu en service."}</p>}<div className="center-card-footer"><small>{simpleActive?"Menu simple configuré dans Administration":flow?.published_at?`Dernière publication le ${new Date(flow.published_at).toLocaleDateString("fr-FR")}`:"Aucune publication"}</small><button className="text-button" onClick={()=>setFlowLine(line)}>{flow?"Modifier le parcours":simpleActive?"Créer un parcours avancé":"Créer le parcours"} <ArrowRight/></button></div></article>;})}{!voiceLines.length&&<EmptyState icon={<Phone/>} title="Ajoutez un numéro vocal"><p>Attribuez un numéro et les droits Appels depuis l’administration.</p></EmptyState>}</div></>}
      {tab==="queues"&&<><div className="admin-toolbar"><div><h3>Vos files d’attente</h3></div><button className="button button-primary" disabled={!voiceLines.length||!data.configured} onClick={()=>setQueueEditor("new")}><Plus/>Créer une file</button></div><div className="admin-lines">{data.queues.map(queue=>{const stat=stats.find(s=>s.queueId===queue.id);return <article className="admin-line" key={queue.id}><h3>{queue.config.name}</h3><p className="admin-help">{formatPhone(admin?.lines.find(l=>l.id===queue.line_id)?.phone_number??"")}</p><div className="center-queue-counts"><span><b>{data.live?stat?.waiting??"—":"—"}</b>en attente</span><span><b>{queue.config.memberIds.length}</b>agents affectés</span><span><b>{data.live?stat?.available??"—":"—"}</b>disponibles</span></div><p className="admin-help">Attente maximale {duration(queue.config.maxWaitSeconds)} · sonnerie {queue.config.ringTimeout} s</p>{!queue.provisioned&&<p className="inline-warning">Provisionnement à terminer. Ouvrez la file et enregistrez-la.</p>}<div className="center-queue-agents">{queue.config.memberIds.map(id=>{const agent=data.agents.find(a=>a.userId===id);return <div key={id}><Avatar name={agent?.name??"Agent"}/><span>{agent?.name??"Agent"}</span><small>{data.live?agent?.activity??"À configurer":"Indisponible"}</small></div>;})}</div><div className="admin-line-actions"><button className="text-button" onClick={()=>setQueueEditor(queue)}>Gérer la file</button><button className="icon-button danger-text" aria-label={`Supprimer ${queue.config.name}`} disabled={busy} onClick={()=>void act(()=>api(`${base}/queues/${queue.id}`,{method:"DELETE"}),"La file a été supprimée.")}><Trash/></button></div></article>;})}</div>{!data.queues.length&&<EmptyState icon={<Headset/>} title="Votre première file"><p>Choisissez ses agents, sa durée d’attente et son débordement.</p></EmptyState>}</>}
      {tab==="agents"&&<><p className="admin-help">Seuls les agents disponibles reçoivent les appels.</p><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Agent</th><th>Statut Twilio</th><th>Réception</th><th>Files</th><th>Actions</th></tr></thead><tbody>{data.agents.map(agent=><tr key={agent.userId}><td><div className="admin-person"><Avatar name={agent.name}/><b>{agent.name}</b></div></td><td><span className={`admin-status ${data.live&&agent.available?"active":""}`}>{data.live?agent.activity:"Indisponible"}</span></td><td>{agent.contactNumber?formatPhone(agent.contactNumber):agent.reachable?"Application connectée":"Aucun appareil prêt"}</td><td>{agent.queueIds.map(id=>data.queues.find(q=>q.id===id)?.config.name).join(", ")}</td><td><button className="text-button" disabled={!data.live} onClick={()=>setAgentEditor(agent)}>Gérer</button></td></tr>)}</tbody></table></div>{!data.agents.length&&<EmptyState icon={<Users/>} title="Aucun agent affecté"><p>Créez une file et sélectionnez ses utilisateurs.</p></EmptyState>}</>}
      {tab==="calls"&&<><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Appelant</th><th>File</th><th>État</th><th>Durée dans le routage</th><th>Priorité</th><th>Actions</th></tr></thead><tbody>{data.tasks.map(task=><tr key={task.sid}><td>{formatPhone(task.caller)||"Appel entrant"}</td><td>{data.queues.find(q=>q.id===task.queueId)?.config.name}</td><td>{labels[task.status]??task.status}{task.workerName&&<small> · {task.workerName}</small>}</td><td>{duration(task.age)}</td><td>{task.priority}</td><td><div className="center-actions"><button className="text-button" disabled={busy||!data.live} onClick={()=>setTransfer(task)}>Transférer</button><button className="text-button" disabled={busy||!data.live||task.status!=="pending"} onClick={()=>void act(()=>api(`${base}/tasks/priority`,{method:"PATCH",body:JSON.stringify({taskSid:task.sid,priority:task.priority?0:10})}),"Priorité mise à jour dans Twilio.")}>{task.priority?"Priorité normale":"Prioriser"}</button></div></td></tr>)}</tbody></table></div>{data.live&&!data.tasks.length&&<EmptyState icon={<Phone/>} title="Aucun appel en cours" />}{!data.live&&<p className="admin-help">La supervision sera disponible lorsque Twilio sera connecté.</p>}</>}
      {tab==="voicemail"&&<><p className="admin-help">50 derniers messages</p>{data.voicemails.map(message=><VoicemailRow key={message.id} message={message} load={()=>audio(`${base}/voicemails/${message.id}/audio`)}/>)}{!data.voicemails.length&&<EmptyState icon={<Voicemail/>} title="Aucun message vocal" />}</>}
    </>}
    {wizard&&admin&&<ChooseLine lines={voiceLines} onClose={()=>setWizard(false)} onChoose={line=>{setWizard(false);setFlowLine(line);}}/>}
    {flowLine&&data&&<FlowEditor line={flowLine} members={admin?.members.filter(m=>m.status==="active"&&admin.assignments.some(a=>a.line_id===flowLine.id&&a.user_id===m.user_id&&a.status==="active"&&a.can_voice))??[]} record={data.flows.find(f=>f.line_id===flowLine.id)} queues={data.queues.filter(q=>q.line_id===flowLine.id)} api={api} base={base} onClose={()=>setFlowLine(null)} onSaved={(published)=>saved(published?"IVR publié sur ce numéro.":"Brouillon enregistré. Le menu en service reste inchangé.")}/>}
    {queueEditor&&admin&&<QueueEditor queue={queueEditor} admin={admin} api={api} base={base} onClose={()=>setQueueEditor(null)} onSaved={()=>saved("La file est synchronisée avec Twilio.")}/>}
    {agentEditor&&<AgentEditor agent={agentEditor} api={api} base={base} onClose={()=>setAgentEditor(null)} onSaved={()=>saved("Statut de l’agent mis à jour dans Twilio.")}/>}
    {transfer&&data&&<TransferEditor task={transfer} queues={data.queues.filter(q=>q.line_id===data.queues.find(q=>q.id===transfer.queueId)?.line_id)} api={api} base={base} onClose={()=>setTransfer(null)} onSaved={()=>saved("Transfert demandé à Twilio. La supervision reflétera son résultat.")}/>}
  </section>;
}
function FormModal({title,onClose,onSubmit,busy,error,children,submitLabel="Enregistrer",wide=false}:{title:string;onClose():void;onSubmit(e:React.FormEvent):void;busy:boolean;error:string;children:ReactNode;submitLabel?:string;wide?:boolean}){
  return <Modal title={title} onClose={onClose} busy={busy} className={wide?"center-editor":""}><form className="contact-form" onSubmit={onSubmit}><fieldset className="admin-fieldset" disabled={busy}>{children}</fieldset>{error&&<p className="form-error" role="alert">{error}</p>}<div className="modal-actions"><button type="button" className="button button-secondary" disabled={busy} onClick={onClose}>Annuler</button><button className="button button-primary" disabled={busy}>{busy?"Synchronisation…":submitLabel}</button></div></form></Modal>;
}
function Destination({value,onChange,queues,menus=[],label="Destination",simple=false}:{value:VoiceDestination;onChange(d:VoiceDestination):void;queues:VoiceQueue[];menus?:VoiceFlow["menus"];label?:string;simple?:boolean}){
  const selected=value.type==="queue"?`queue:${value.queueId}`:value.type==="menu"?`menu:${value.menuId}`:value.type;
  return <div className="center-destination"><label className="field-label">{label}<select value={selected} onChange={e=>{const [type,id]=e.target.value.split(":");onChange(type==="queue"?{type,queueId:id!}:type==="menu"?{type,menuId:id!}:type==="number"?{type,number:""}:{type:type as "voicemail"|"hangup"});}}><option value="voicemail">Messagerie vocale</option><option value="number">Renvoi vers un numéro externe</option><option value="hangup">Au revoir et raccrocher</option>{!simple&&queues.map(q=><option key={q.id} value={`queue:${q.id}`}>File · {q.config.name}</option>)}{!simple&&menus.map(m=><option key={m.id} value={`menu:${m.id}`}>Menu · {m.name}</option>)}</select></label>{value.type==="number"&&<label className="field-label">Numéro de destination<input type="tel" required placeholder="+33123456789" value={value.number} onChange={e=>onChange({type:"number",number:e.target.value})}/></label>}</div>;
}
function AgentChecks({admin,lineId,ids,onChange}:{admin:AdminSnapshot;lineId:string;ids:string[];onChange(ids:string[]):void}){
  const members=admin.members.filter(m=>m.status==="active"&&admin.assignments.some(a=>a.line_id===lineId&&a.user_id===m.user_id&&a.status==="active"&&a.can_voice));
  return <div className="center-member-picker">{members.map(m=><label className="admin-check" key={m.user_id}><input type="checkbox" checked={ids.includes(m.user_id)} onChange={e=>onChange(e.target.checked?[...ids,m.user_id]:ids.filter(id=>id!==m.user_id))}/><Avatar name={m.display_name}/><span>{m.display_name}</span></label>)}{!members.length&&<p className="inline-warning">Attribuez d’abord le droit Appels de ce numéro à un utilisateur dans Administration → Numéros.</p>}</div>;
}
function ChooseLine({lines,onClose,onChoose}:{lines:AdminLine[];onClose():void;onChoose(line:AdminLine):void}){
  const [id,setId]=useState(lines[0]?.id??"");
  return <FormModal title="Créer votre parcours d’appel" onClose={onClose} busy={false} error="" submitLabel="Ouvrir l’éditeur" onSubmit={event=>{event.preventDefault();const line=lines.find(item=>item.id===id);if(line)onChoose(line);}}><label className="field-label">Numéro de téléphone<select value={id} onChange={event=>setId(event.target.value)}>{lines.map(line=><option key={line.id} value={line.id}>{formatPhone(line.phone_number)}</option>)}</select></label></FormModal>;
}
function QueueEditor({queue,admin,api,base,onClose,onSaved}:{queue:VoiceQueue|"new";admin:AdminSnapshot;api:Api;base:string;onClose():void;onSaved():Promise<void>}){
  const [config,setConfig]=useState(queue==="new"?queueDefaults():structuredClone(queue.config)),[lineId,setLineId]=useState(queue==="new"?admin.lines.find(l=>l.status==="active"&&l.voice_enabled)?.id??"":queue.line_id),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const id=useRef(queue==="new"?crypto.randomUUID():queue.id),version=useRef(queue==="new"?0:queue.version);
  async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{const parsed=queueConfigSchema.safeParse(config);if(!parsed.success)throw new Error(parsed.error.issues[0]?.message);await api(`${base}/queues/${id.current}`,{method:"PUT",body:JSON.stringify({lineId,version:version.current,config:parsed.data})});await onSaved();}catch(e){setError(errorText(e));try{const current=await api<CenterSnapshot>(base);version.current=current.queues.find(q=>q.id===id.current)?.version??version.current;}catch{}}finally{setBusy(false);}}
  return <FormModal title={queue==="new"?"Nouvelle file d’attente":`File · ${queue.config.name}`} onClose={onClose} onSubmit={submit} busy={busy} error={error} wide><div className="admin-form-grid"><label className="field-label">Nom<input required maxLength={80} value={config.name} onChange={e=>setConfig({...config,name:e.target.value})}/></label><label className="field-label">Numéro<select disabled={queue!=="new"} value={lineId} onChange={e=>{setLineId(e.target.value);setConfig({...config,memberIds:[]});}}>{admin.lines.filter(l=>l.voice_enabled&&l.status==="active").map(l=><option key={l.id} value={l.id}>{formatPhone(l.phone_number)}</option>)}</select></label></div><h3>Agents de la file</h3><AgentChecks admin={admin} lineId={lineId} ids={config.memberIds} onChange={memberIds=>setConfig({...config,memberIds})}/><div className="admin-form-grid"><label className="field-label">Attente maximale (secondes)<input type="number" min={15} max={3600} required value={config.maxWaitSeconds} onChange={e=>setConfig({...config,maxWaitSeconds:Number(e.target.value)})}/></label><label className="field-label">Sonnerie par agent (secondes)<input type="number" min={5} max={60} required value={config.ringTimeout} onChange={e=>setConfig({...config,ringTimeout:Number(e.target.value)})}/></label></div><label className="field-label">Annonce d’attente<textarea required rows={2} maxLength={1000} value={config.holdMessage} onChange={e=>setConfig({...config,holdMessage:e.target.value})}/></label><label className="field-label">Musique d’attente · URL HTTPS (facultatif)<input type="url" placeholder="https://…/musique.mp3" value={config.holdMusicUrl??""} onChange={e=>setConfig({...config,holdMusicUrl:e.target.value||null})}/></label><label className="admin-check"><input type="checkbox" checked={config.announcePosition} onChange={e=>setConfig({...config,announcePosition:e.target.checked})}/>Annoncer la position dans la file</label><Destination value={config.overflow} onChange={overflow=>setConfig({...config,overflow:overflow as QueueConfig["overflow"]})} queues={[]} simple label="À la fin de l’attente"/></FormModal>;
}
function AgentEditor({agent,api,base,onClose,onSaved}:{agent:CenterAgent;api:Api;base:string;onClose():void;onSaved():Promise<void>}){
  const [activity,setActivity]=useState(agent.available?"available":agent.activity==="En pause"?"break":"offline"),[contactNumber,setContactNumber]=useState(agent.contactNumber??""),[busy,setBusy]=useState(false),[error,setError]=useState("");
  async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{await api(`${base}/agents/${agent.userId}`,{method:"PUT",body:JSON.stringify({activity,contactNumber:contactNumber||null})});await onSaved();}catch(e){setError(errorText(e));}finally{setBusy(false);}}
  return <FormModal title={agent.name} onClose={onClose} onSubmit={submit} busy={busy} error={error}><p className="admin-help">Statut actuel : {agent.activity}</p><label className="field-label">Statut<select value={activity} onChange={e=>setActivity(e.target.value)}><option value="available">Disponible</option><option value="break">En pause</option><option value="offline">Hors ligne</option></select></label><label className="field-label">Recevoir sur un numéro externe (facultatif)<input type="tel" placeholder="+33612345678" value={contactNumber} onChange={e=>setContactNumber(e.target.value)}/><small className="admin-help">Laissez vide pour recevoir dans l’application de l’agent.</small></label></FormModal>;
}
function TransferEditor({task,queues,api,base,onClose,onSaved}:{task:CenterTask;queues:VoiceQueue[];api:Api;base:string;onClose():void;onSaved():Promise<void>}){
  const [destination,setDestination]=useState<VoiceDestination>({type:"number",number:""}),[busy,setBusy]=useState(false),[error,setError]=useState("");const operationId=useRef(crypto.randomUUID());
  async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{await api(`${base}/tasks/transfer`,{method:"POST",body:JSON.stringify({taskSid:task.sid,operationId:operationId.current,destination})});await onSaved();}catch(e){setError(errorText(e));}finally{setBusy(false);}}
  return <FormModal title={`Transférer ${formatPhone(task.caller)}`} onClose={onClose} onSubmit={submit} busy={busy} error={error} submitLabel="Transférer l’appel"><p className="admin-help">L’appelant sera immédiatement dirigé vers cette destination. La conversation avec l’agent actuel prendra fin.</p><Destination value={destination} onChange={setDestination} queues={queues}/></FormModal>;
}
function VoicemailRow({message,load}:{message:CenterSnapshot["voicemails"][number];load():Promise<Blob>}){
  const [url,setUrl]=useState<string|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);const alive=useRef(true);
  useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
  useEffect(()=>()=>{if(url)URL.revokeObjectURL(url);},[url]);
  return <article className="center-voicemail"><Voicemail size={24}/><div><b>{formatPhone(message.caller)}</b><p>{new Date(message.created_at).toLocaleString("fr-FR")} · {duration(message.duration)}</p>{error&&<p className="form-error">{error}</p>}</div>{url?<audio controls src={url}/>:<button className="button button-secondary" disabled={busy} onClick={async()=>{setBusy(true);try{const blob=await load();if(alive.current)setUrl(URL.createObjectURL(blob));}catch(e){if(alive.current)setError(errorText(e));}finally{if(alive.current)setBusy(false);}}}>{busy?"Chargement…":"Écouter"}</button>}</article>;
}
