import { useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import { ArrowClockwise, ArrowDownLeft, ArrowUpRight, CalendarBlank, CaretDown, ChartBar, CheckCircle, Clock, DownloadSimple, Funnel, GitBranch, Info, MagnifyingGlass, Phone, Users, Voicemail, X } from "@phosphor-icons/react";
import type { StatisticsSnapshot } from "@onoff/contracts";
import { Avatar, EmptyState, Modal } from "./ui";
import { formatPhone } from "./conversation-model";
import { csv, dailySeries, dateInZone, defaultFilters, duration, filterCalls, heatmap, outcome, OUTCOMES, percentage, periodDays, previousPeriod, queryWindow, shiftDate, summarize, timedCalls, validateFilters, WEEKDAYS, type HeatMetric, type StatisticsFilters, type TimedCall } from "./statistics-model";
import "./statistics.css";

type Api = <T>(path: string, init?: RequestInit) => Promise<T>;
type Tab = "overview" | "calls" | "people" | "voice";
const TABS: { id: Tab; label: string; icon: ReactNode }[] = [
  { id: "overview", label: "Vue d’ensemble", icon: <ChartBar/> }, { id: "calls", label: "Appels", icon: <Phone/> },
  { id: "people", label: "Équipes & utilisateurs", icon: <Users/> }, { id: "voice", label: "IVR & vocal", icon: <GitBranch/> },
];
const number = (value: number) => new Intl.NumberFormat("fr-FR").format(value);
const EMPTY: StatisticsSnapshot = { fetchedAt: "", from: "", to: "", calls: [], users: [], teams: [], lines: [] };

export function Statistics({ organizationId, api, refreshKey = 0 }: { organizationId: string; api: Api; refreshKey?: number }) {
  const [filters, setFilters] = useState(defaultFilters), [tab, setTab] = useState<Tab>("overview");
  const [snapshot, setSnapshot] = useState<StatisticsSnapshot | null>(null), [state, setState] = useState<"loading" | "ready" | "error">("loading"), [error, setError] = useState("");
  const [advanced, setAdvanced] = useState(false), [compare, setCompare] = useState(true), [reload, setReload] = useState(0), [definitions, setDefinitions] = useState(false);
  const [heatMetric, setHeatMetric] = useState<HeatMetric>("volume");
  const apiRef = useRef(api); apiRef.current = api;
  const invalid = validateFilters(filters);
  const validPeriod = Number.isFinite(periodDays(filters.from, filters.to)) && periodDays(filters.from, filters.to) > 0 && periodDays(filters.from, filters.to) <= 90;
  const window = validPeriod ? queryWindow(filters) : null;
  const windowFrom = window?.from, windowTo = window?.to;
  useEffect(() => {
    if (!windowFrom || !windowTo) return;
    const controller = new AbortController();
    setState("loading"); setError("");
    const timer = setTimeout(() => {
      void apiRef.current<StatisticsSnapshot>(`/v1/organizations/${organizationId}/statistics?${new URLSearchParams({ from: windowFrom, to: windowTo })}`, { signal: controller.signal })
        .then(data => { if (!controller.signal.aborted) { setSnapshot(data); setState("ready"); } })
        .catch(reason => { if (!controller.signal.aborted) { setSnapshot(null); setState("error"); setError(reason instanceof Error ? reason.message : "Les statistiques sont indisponibles."); } });
    }, 180);
    return () => { clearTimeout(timer); controller.abort(); };
  }, [organizationId, windowFrom, windowTo, refreshKey, reload]);
  const data = snapshot ?? EMPTY;
  const all = useMemo(() => timedCalls(data.calls, filters.timezone), [data.calls, filters.timezone]);
  const calls = useMemo(() => invalid ? [] : filterCalls(all, filters, data.teams), [all, filters, data.teams, invalid]);
  const previous = useMemo(() => invalid ? [] : filterCalls(all, filters, data.teams, previousPeriod(filters)), [all, filters, data.teams, invalid]);
  const summary = summarize(calls), before = summarize(previous);
  const available = state === "ready" && !invalid && snapshot?.from === windowFrom && snapshot?.to === windowTo;
  function change<K extends keyof StatisticsFilters>(key: K, value: StatisticsFilters[K]) { setFilters(current => ({ ...current, [key]: value })); }
  function preset(days: number) { const to = dateInZone(new Date(), filters.timezone); setFilters(current => ({ ...current, from: shiftDate(to, 1 - days), to })); }
  function drill(patch: Partial<StatisticsFilters>) { setFilters(current => ({ ...current, ...patch })); setTab("calls"); }
  const activeFilters: { label: string; clear(): void }[] = [
    ...filters.userIds.map(id => ({ label: id === "unassigned" ? "Non attribué" : data.users.find(user => user.id === id)?.name ?? id, clear: () => change("userIds", filters.userIds.filter(value => value !== id)) })),
    ...filters.teamIds.map(id => ({ label: data.teams.find(team => team.id === id)?.name ?? id, clear: () => change("teamIds", filters.teamIds.filter(value => value !== id)) })),
    ...filters.lineIds.map(id => ({ label: formatPhone(data.lines.find(line => line.id === id)?.number ?? id), clear: () => change("lineIds", filters.lineIds.filter(value => value !== id)) })),
    ...(filters.direction !== "all" ? [{ label: filters.direction === "inbound" ? "Entrants" : "Sortants", clear: () => change("direction", "all") }] : []),
    ...(filters.outcome !== "all" ? [{ label: OUTCOMES[filters.outcome as keyof typeof OUTCOMES], clear: () => change("outcome", "all") }] : []),
    ...(filters.routing !== "all" ? [{ label: filters.routing === "direct" ? "Appels directs" : filters.routing === "ivr" ? "IVR classique" : "Parcours avancé", clear: () => change("routing", "all") }] : []),
    ...(filters.weekdays.length ? [{ label: filters.weekdays.map(day => WEEKDAYS[day]).join(", "), clear: () => change("weekdays", []) }] : []),
    ...(filters.startHour !== 0 || filters.endHour !== 24 ? [{ label: `${filters.startHour} h – ${filters.endHour} h`, clear: () => setFilters(current => ({ ...current, startHour: 0, endHour: 24 })) }] : []),
    ...(filters.minDuration || filters.maxDuration ? [{ label: `Durée : ${filters.minDuration || "0"}–${filters.maxDuration || "∞"} s`, clear: () => setFilters(current => ({ ...current, minDuration: "", maxDuration: "" })) }] : []),
    ...(filters.search ? [{ label: filters.search, clear: () => change("search", "") }] : []),
  ];
  function exportCsv() {
    const blob = new Blob([csv(calls, data, filters.timezone)], { type: "text/csv;charset=utf-8" }), url = URL.createObjectURL(blob);
    const anchor = document.createElement("a"); anchor.href = url; anchor.download = `onoff-statistiques-${filters.from}-${filters.to}.csv`; anchor.click();
    setTimeout(() => URL.revokeObjectURL(url), 1000);
  }
  return <section className="stats-page" aria-label="Statistiques détaillées">
    <div className="stats-heading"><div><span className="stats-eyebrow">ANALYSE DE L’ACTIVITÉ</span><h2>Votre activité en détail.</h2><p>Comprenez vos volumes, vos équipes et vos parcours vocaux.</p></div><div className="stats-heading-actions"><button className="icon-button" aria-label="Définitions des indicateurs" onClick={() => setDefinitions(true)}><Info/></button><button className="button button-secondary" disabled={!available || !calls.length} onClick={exportCsv}><DownloadSimple size={17}/>Exporter les appels</button></div></div>
    <div className="stats-period">
      <div className="stats-date-range"><CalendarBlank size={18}/><label><span className="stats-sr">Date de début</span><input aria-label="Date de début" type="date" value={filters.from} onChange={event => change("from", event.target.value)}/></label><span>au</span><label><span className="stats-sr">Date de fin</span><input aria-label="Date de fin" type="date" value={filters.to} onChange={event => change("to", event.target.value)}/></label></div>
      <div className="stats-presets">{[1, 7, 30, 90].map(days => <button key={days} className={filters.to === dateInZone(new Date(), filters.timezone) && periodDays(filters.from, filters.to) === days ? "active" : ""} onClick={() => preset(days)}>{days === 1 ? "Aujourd’hui" : `${days} jours`}</button>)}</div>
      <label className="stats-compare"><input type="checkbox" checked={compare} onChange={event => setCompare(event.target.checked)}/>Comparer à la période précédente</label>
    </div>
    <nav className="stats-tabs" aria-label="Vues statistiques">{TABS.map(item => <button key={item.id} aria-current={tab === item.id ? "page" : undefined} className={tab === item.id ? "active" : ""} onClick={() => setTab(item.id)}>{item.icon}{item.label}</button>)}</nav>
    <div className="stats-filter-bar">
      <MultiFilter label="Utilisateurs" items={[...data.users.map(user => ({ id: user.id, label: user.name })), { id: "unassigned", label: "Non attribué" }]} selected={filters.userIds} onChange={value => change("userIds", value)}/>
      <MultiFilter label="Équipes" items={data.teams.map(team => ({ id: team.id, label: team.name }))} selected={filters.teamIds} onChange={value => change("teamIds", value)} hint="Groupes issus des membres actuels des files. Ce filtre ne désigne pas la file traversée par l’appel."/>
      <MultiFilter label="Lignes" items={data.lines.map(line => ({ id: line.id, label: formatPhone(line.number) }))} selected={filters.lineIds} onChange={value => change("lineIds", value)}/>
      <label className="stats-inline-select"><span>Sens</span><select aria-label="Sens des appels" value={filters.direction} onChange={event => change("direction", event.target.value)}><option value="all">Tous les appels</option><option value="inbound">Entrants · inbound</option><option value="outbound">Sortants · outbound</option></select></label>
      <button className={`button button-secondary stats-more${advanced ? " active" : ""}`} aria-expanded={advanced} aria-controls="statistics-advanced" onClick={() => setAdvanced(value => !value)}><Funnel size={16}/>Filtres avancés{activeFilters.length > 0 && <b>{activeFilters.length}</b>}</button>
    </div>
    {advanced && <div className="stats-advanced" id="statistics-advanced">
      <label>Résultat<select value={filters.outcome} onChange={event => change("outcome", event.target.value)}><option value="all">Tous les résultats</option>{Object.entries(OUTCOMES).map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></label>
      <label>Parcours<select value={filters.routing} onChange={event => change("routing", event.target.value)}><option value="all">Tous les parcours</option><option value="direct">Appel direct</option><option value="ivr">IVR classique</option><option value="center">IVR / parcours avancé</option></select></label>
      <label>Durée minimale (s)<input type="number" min="0" placeholder="Sans minimum" value={filters.minDuration} onChange={event => change("minDuration", event.target.value)}/></label>
      <label>Durée maximale (s)<input type="number" min="0" placeholder="Sans maximum" value={filters.maxDuration} onChange={event => change("maxDuration", event.target.value)}/></label>
      <label>À partir de<select value={filters.startHour} onChange={event => change("startHour", Number(event.target.value))}>{Array.from({ length: 24 }, (_, hour) => <option key={hour} value={hour}>{hour} h</option>)}</select></label>
      <label>Jusqu’à<select value={filters.endHour} onChange={event => change("endHour", Number(event.target.value))}>{Array.from({ length: 24 }, (_, index) => <option key={index + 1} value={index + 1}>{index + 1} h</option>)}</select></label>
      <label>Fuseau horaire<select value={filters.timezone} onChange={event => change("timezone", event.target.value)}><option>Europe/Paris</option><option>Europe/London</option><option>America/New_York</option><option>UTC</option></select></label>
      <label>Numéro distant<div className="stats-search"><MagnifyingGlass size={16}/><input placeholder="Rechercher un numéro" value={filters.search} onChange={event => change("search", event.target.value)}/></div></label>
      <fieldset className="stats-weekdays"><legend>Jours de la semaine</legend>{WEEKDAYS.map((day, index) => <button key={day} aria-pressed={filters.weekdays.includes(index)} onClick={() => change("weekdays", filters.weekdays.includes(index) ? filters.weekdays.filter(value => value !== index) : [...filters.weekdays, index])}>{day}</button>)}</fieldset>
    </div>}
    {!!activeFilters.length && <div className="stats-chips">{activeFilters.map((filter, index) => <button key={`${filter.label}-${index}`} onClick={filter.clear}>{filter.label}<X size={12}/><span className="stats-sr">Retirer le filtre</span></button>)}<button className="stats-reset" onClick={() => setFilters(current => ({ ...defaultFilters(), from: current.from, to: current.to, timezone: current.timezone }))}>Tout effacer</button></div>}
    {invalid ? <p className="stats-error" role="alert">{invalid}</p> : state === "error" ? <div className="stats-error" role="alert"><p>{error}</p><button className="button button-secondary" onClick={() => setReload(value => value + 1)}><ArrowClockwise size={16}/>Réessayer</button></div> : !available ? <div className="stats-loading" role="status"><ChartBar size={30}/><h3>Préparation des statistiques…</h3><p>Chargement de la période et de sa comparaison.</p></div> : <>
      <div className="stats-scope"><span><i/>{number(calls.length)} appels dans cette sélection</span><span>{filters.timezone} · Actualisé à {new Date(data.fetchedAt).toLocaleTimeString("fr-FR", { hour: "2-digit", minute: "2-digit", timeZone: filters.timezone })}</span></div>
      <div className="stats-kpis">
        <Kpi label="Volume d’appels" value={number(summary.total)} previous={compare ? before.total : undefined} current={summary.total} icon={<Phone/>} note={`${number(summary.inbound)} entrants · ${number(summary.outbound)} sortants`}/>
        <Kpi label="Mises en relation" value={percentage(summary.connectionRate)} previous={compare ? before.connectionRate : undefined} current={summary.connectionRate} points icon={<CheckCircle/>} note={`${number(summary.connected)} connexions confirmées`} title="Appels terminés avec connexion confirmée / tous les appels terminés. Répondre dans l’IVR ne compte pas comme une connexion."/>
        <Kpi label="Durée moyenne" value={duration(summary.averageDuration)} previous={compare ? before.averageDuration : undefined} current={summary.averageDuration} icon={<Clock/>} note={`${number(summary.durationSamples)} durées mesurées`} title="Moyenne des durées de conversation renseignées. Les durées inconnues sont exclues."/>
        <Kpi label="Appels manqués" value={number(summary.missed)} previous={compare ? before.missed : undefined} current={summary.missed} icon={<ArrowDownLeft/>} note="Sans réponse ou annulés"/>
      </div>
      {tab === "overview" && <>
        <div className="stats-chart-grid"><DailyChart calls={calls} from={filters.from} to={filters.to}/><OutcomeChart calls={calls} onSelect={value => drill({ outcome: value })}/></div>
        <Heatmap calls={calls} metric={heatMetric} onMetric={setHeatMetric} timezone={filters.timezone} onSelect={(weekday, hour) => drill({ weekdays: [weekday], startHour: hour, endHour: hour + 1 })}/>
        <div className="stats-bottom-grid"><div className="stats-panel stats-duration-summary"><SectionTitle title="Le temps au téléphone" subtitle="Durées de conversation mesurées"/><strong>{duration(summary.totalDuration)}</strong><p>Durée cumulée sur {number(summary.durationSamples)} appels.</p><DurationDistribution calls={calls}/></div><PeopleTable calls={calls} data={data} compact onSelect={id => drill({ userIds: [id] })}/></div>
      </>}
      {tab === "calls" && <><Heatmap calls={calls} metric={heatMetric} onMetric={setHeatMetric} timezone={filters.timezone} onSelect={(weekday, hour) => drill({ weekdays: [weekday], startHour: hour, endHour: hour + 1 })}/><CallTable key={JSON.stringify(filters)} calls={calls} data={data} timezone={filters.timezone}/></>}
      {tab === "people" && <><PeopleTable calls={calls} data={data} onSelect={id => drill({ userIds: [id] })}/><p className="stats-note"><Info size={16}/>L’attribution repose sur l’appareil émetteur ou ayant répondu. Les agents non identifiables restent dans « Non attribué ». Les équipes utilisent les membres actuels des files et peuvent se recouper.</p></>}
      {tab === "voice" && <VoiceStatistics calls={calls}/>}
      <footer className="stats-footer"><span>Les filtres s’appliquent à tous les indicateurs et à l’export.</span><button className="text-button" onClick={() => setDefinitions(true)}><Info size={15}/>Comprendre les chiffres</button></footer>
    </>}
    {definitions && <Modal title="Comprendre les statistiques" onClose={() => setDefinitions(false)} className="stats-definitions"><div className="stats-definition-list"><h3>Période & comparaison</h3><p>Les appels sont rattachés à leur date de création dans le fuseau choisi. La comparaison porte sur les mêmes filtres pendant les {validPeriod ? periodDays(filters.from, filters.to) : "N"} jours précédents. La journée en cours est partielle. « — » indique une mesure indisponible ou une base de comparaison nulle.</p><h3>Mise en relation</h3><p>Une connexion est confirmée par une branche d’appel ayant répondu ou par une sortie de file / de renvoi réussie. Le taux utilise uniquement les appels terminés. L’accueil automatique de l’IVR ne suffit pas.</p><h3>Durées</h3><p>Les durées proviennent des conversations mesurées, sans remplacer les valeurs manquantes par zéro. Ce ne sont ni des durées d’attente ni des durées de traitement avec travail après appel.</p><h3>Utilisateurs & équipes</h3><p>Les appels sortants sont attribués à leur émetteur, les entrants aux appareils ayant répondu. Un appel peut avoir plusieurs utilisateurs. Les totaux des lignes utilisateurs ou équipes ne sont donc pas nécessairement additionnables. Les équipes reflètent les membres actuels des files, pas les files historiquement traversées.</p><h3>IVR & vocal</h3><p>Les parcours avancés incluent les routages sans menu. Les événements détaillés de navigation, attente, abandon et écoute des messages ne sont pas mesurés. Les transferts comptent les demandes enregistrées, sans garantie de réussite.</p><h3>Export</h3><p>Le CSV contient tous les appels filtrés, avec leurs durées en secondes. Les données chargées sont limitées à 20 000 appels, comparaison comprise ; au-delà, réduisez la période.</p></div></Modal>}
  </section>;
}

function MultiFilter({ label, items, selected, onChange, hint }: { label: string; items: { id: string; label: string }[]; selected: string[]; onChange(value: string[]): void; hint?: string }) {
  return <details className="stats-multi"><summary>{label}{selected.length ? <b>{selected.length}</b> : null}<CaretDown size={13}/></summary><div className="stats-multi-menu">{hint && <p>{hint}</p>}{items.length ? items.map(item => <label key={item.id}><input type="checkbox" checked={selected.includes(item.id)} onChange={() => onChange(selected.includes(item.id) ? selected.filter(id => id !== item.id) : [...selected, item.id])}/>{item.label}</label>) : <p>Aucune équipe configurée.</p>}{!!selected.length && <button className="text-button" onClick={() => onChange([])}>Effacer la sélection</button>}</div></details>;
}
function Kpi({ label, value, current, previous, points, note, icon, title }: { label: string; value: string; current: number | null; previous?: number | null | undefined; points?: boolean; note: string; icon: ReactNode; title?: string }) {
  const rawDelta = current !== null && previous !== undefined && previous !== null && (points || previous > 0) ? points ? current - previous : (current - previous) / previous * 100 : null;
  const delta = rawDelta === null ? null : Math.round(rawDelta * 10) / 10 || 0;
  return <article className="stats-kpi" title={title}><div className="stats-kpi-label"><span>{label}</span>{icon}</div><div className="stats-kpi-value"><strong>{value}</strong>{previous !== undefined && <span className="stats-delta" title="Évolution par rapport à la période précédente">{delta === null ? "—" : `${delta > 0 ? "+" : ""}${new Intl.NumberFormat("fr-FR", { maximumFractionDigits: 1 }).format(delta)} ${points ? "pts" : "%"}`}</span>}</div><p>{note}</p></article>;
}
function SectionTitle({ title, subtitle, children }: { title: string; subtitle: string; children?: ReactNode }) { return <div className="stats-section-title"><div><h3>{title}</h3><p>{subtitle}</p></div>{children}</div>; }
function DailyChart({ calls, from, to }: { calls: TimedCall[]; from: string; to: string }) {
  const series = dailySeries(calls, from, to), maximum = Math.max(1, ...series.map(day => day.inbound + day.outbound));
  return <section className="stats-panel"><SectionTitle title="Le rythme de vos appels" subtitle="Volume quotidien, entrants et sortants"><div className="stats-legend"><span><i/>Entrants</span><span><i className="outbound"/>Sortants</span></div></SectionTitle><div className="stats-daily-chart" role="img" aria-label={`${calls.length} appels répartis du ${from} au ${to}`}><div className="stats-y-axis"><span>{number(maximum)}</span><span>{number(Math.round(maximum / 2))}</span><span>0</span></div><div className="stats-daily-plot">{series.map((day, index) => <div className="stats-day" key={day.date} tabIndex={0} aria-label={`${day.date} : ${day.inbound} entrants, ${day.outbound} sortants`} title={`${day.date} · ${day.inbound} entrants · ${day.outbound} sortants`}><div className="stats-day-bar"><i className="stats-bar-outbound" style={{ height: `${day.outbound / maximum * 100}%` }}/><i className="stats-bar-inbound" style={{ height: `${day.inbound / maximum * 100}%` }}/></div><span>{index === 0 || index === series.length - 1 || index % Math.max(1, Math.ceil(series.length / 6)) === 0 ? `${day.date.slice(8)}/${day.date.slice(5, 7)}` : ""}</span></div>)}</div></div>{!calls.length && <p className="stats-chart-empty">Aucun appel sur cette sélection.</p>}</section>;
}
function OutcomeChart({ calls, onSelect }: { calls: TimedCall[]; onSelect(value: string): void }) {
  return <section className="stats-panel"><SectionTitle title="À l’issue de l’appel" subtitle="Explorez chaque résultat"/><div className="stats-outcomes">{Object.entries(OUTCOMES).map(([key, label]) => { const count = calls.filter(call => outcome(call) === key).length; return <button key={key} onClick={() => onSelect(key)}><span><i className={`stats-outcome-dot ${key}`}/>{label}<b>{number(count)}</b></span><span className="stats-outcome-track"><i className={key} style={{ width: `${calls.length ? count / calls.length * 100 : 0}%` }}/></span></button>; })}</div></section>;
}
function Heatmap({ calls, metric, onMetric, timezone, onSelect }: { calls: TimedCall[]; metric: HeatMetric; onMetric(value: HeatMetric): void; timezone: string; onSelect(day: number, hour: number): void }) {
  const cells = heatmap(calls, metric), maximum = Math.max(1, ...cells.map(cell => cell.value ?? 0));
  const valueText = (value: number | null) => metric === "duration" ? duration(value) : metric === "connection" ? percentage(value) : `${number(value ?? 0)} appels`;
  const peak = cells.filter(cell => cell.count && cell.value !== null).sort((a, b) => b.value! - a.value!)[0];
  const [hover, setHover] = useState<string | null>(null);
  return <section className="stats-panel stats-heatmap-panel"><SectionTitle title="Activité par jour et par heure" subtitle={`Heatmap par jour et par heure · ${timezone}`}><select aria-label="Mesure de la heatmap" value={metric} onChange={event => onMetric(event.target.value as HeatMetric)}><option value="volume">Volume d’appels</option><option value="missed">Appels manqués</option><option value="duration">Durée moyenne</option><option value="connection">Taux de mise en relation</option></select></SectionTitle><div className="stats-heatmap-scroll"><div className="stats-heatmap"><span/>{Array.from({ length: 24 }, (_, hour) => <span className="stats-heat-hour" key={`h${hour}`}>{String(hour).padStart(2, "0")}</span>)}{WEEKDAYS.map((day, weekday) => <div className="stats-heat-row" key={day}><span className="stats-heat-day">{day}</span>{cells.filter(cell => cell.weekday === weekday).map(cell => {
    const level = !cell.count || cell.value === null || cell.value === 0 ? 0 : Math.max(1, Math.ceil(cell.value / maximum * 5));
    const label = `${day} ${cell.hour} h – ${cell.hour + 1} h : ${valueText(cell.value)} · ${cell.count} appels dans la cellule`;
    return <button key={cell.hour} className={`stats-heat-cell level-${level}`} aria-label={label} title={label} onMouseEnter={() => setHover(label)} onMouseLeave={() => setHover(null)} onFocus={() => setHover(label)} onBlur={() => setHover(null)} disabled={!cell.count} onClick={() => onSelect(weekday, cell.hour)}/>;
  })}</div>)}</div></div><div className="stats-heatmap-footer"><p aria-live="polite">{hover ?? (peak ? `${WEEKDAYS[peak.weekday]} ${peak.hour} h : ${valueText(peak.value)}. Cliquez sur une case pour voir les appels.` : "Les créneaux se rempliront avec vos appels.")}</p><div className="stats-heat-scale"><span>Faible</span>{[0, 1, 2, 3, 4, 5].map(level => <i key={level} className={`level-${level}`}/>)}<span>Élevé</span></div></div></section>;
}
function DurationDistribution({ calls }: { calls: TimedCall[] }) {
  const values = calls.flatMap(call => call.durationSeconds === null ? [] : [call.durationSeconds]), ranges = [{ label: "< 1 min", min: 0, max: 60 }, { label: "1–3 min", min: 60, max: 180 }, { label: "3–10 min", min: 180, max: 600 }, { label: "≥ 10 min", min: 600, max: Infinity }];
  return <div className="stats-duration-bins">{ranges.map(range => { const count = values.filter(value => value >= range.min && value < range.max).length; return <div key={range.label}><b>{number(count)}</b><span>{range.label}</span></div>; })}</div>;
}
function PeopleTable({ calls, data, compact = false, onSelect }: { calls: TimedCall[]; data: StatisticsSnapshot; compact?: boolean; onSelect(id: string): void }) {
  const [group, setGroup] = useState("users");
  const groups = group === "teams" ? data.teams.map(team => ({ id: team.id, name: team.name, calls: calls.filter(call => call.userIds.some(id => team.userIds.includes(id))) })) : group === "lines" ? data.lines.map(line => ({ id: line.id, name: formatPhone(line.number), calls: calls.filter(call => call.lineId === line.id) })) : [...data.users.map(user => ({ ...user, calls: calls.filter(call => call.userIds.includes(user.id)) })), { id: "unassigned", name: "Non attribué", calls: calls.filter(call => !call.userIds.length) }];
  const rows = groups.map(item => ({ ...item, stats: summarize(item.calls) })).sort((a, b) => b.stats.total - a.stats.total || a.name.localeCompare(b.name));
  return <section className="stats-panel stats-people"><SectionTitle title={compact ? "L’activité de l’équipe" : "La contribution de chacun"} subtitle={group === "teams" ? "Membres actuels des files · groupes non exclusifs" : "Appels attribués et durées mesurées"}>{!compact && <select aria-label="Regrouper les statistiques" value={group} onChange={event => setGroup(event.target.value)}><option value="users">Par utilisateur</option><option value="teams">Par équipe / file actuelle</option><option value="lines">Par ligne</option></select>}</SectionTitle><div className="stats-table-scroll"><table className="stats-table"><thead><tr><th>{group === "users" ? "Utilisateur" : group === "teams" ? "Équipe" : "Ligne"}</th><th>Appels</th>{!compact && <><th>Entrants</th><th>Sortants</th></>}<th>Connexion</th>{!compact && <><th>Durée moy.</th><th>Durée totale</th></>}</tr></thead><tbody>{rows.slice(0, compact ? 4 : undefined).map(row => <tr key={row.id}><td>{group === "users" ? <button className="stats-person" onClick={() => onSelect(row.id)}><Avatar name={row.name}/><span>{row.name}</span></button> : row.name}</td><td>{number(row.stats.total)}</td>{!compact && <><td>{number(row.stats.inbound)}</td><td>{number(row.stats.outbound)}</td></>}<td>{percentage(row.stats.connectionRate)}</td>{!compact && <><td>{duration(row.stats.averageDuration)}</td><td>{duration(row.stats.totalDuration)}</td></>}</tr>)}</tbody></table>{!rows.length && <p className="stats-chart-empty">Aucun groupe disponible.</p>}</div></section>;
}
function CallTable({ calls, data, timezone }: { calls: TimedCall[]; data: StatisticsSnapshot; timezone: string }) {
  const [page, setPage] = useState(0), [sort, setSort] = useState("recent"), [selected, setSelected] = useState<TimedCall | null>(null);
  const sorted = useMemo(() => [...calls].sort((a, b) => sort === "duration" ? (b.durationSeconds ?? -1) - (a.durationSeconds ?? -1) : b.createdAt.localeCompare(a.createdAt)), [calls, sort]);
  const pages = Math.max(1, Math.ceil(calls.length / 15)), currentPage = Math.min(page, pages - 1);
  const userNames = (call: TimedCall) => call.userIds.map(id => data.users.find(user => user.id === id)?.name ?? "Utilisateur supprimé").join(", ") || "Non attribué";
  return <section className="stats-panel"><SectionTitle title="Journal des appels" subtitle={`${number(calls.length)} appels correspondent à vos filtres`}><select aria-label="Trier les appels" value={sort} onChange={event => { setSort(event.target.value); setPage(0); }}><option value="recent">Plus récents</option><option value="duration">Durée décroissante</option></select></SectionTitle>{!calls.length ? <EmptyState icon={<MagnifyingGlass/>} title="Aucun appel ne correspond"><p>Essayez une autre période ou retirez un filtre.</p></EmptyState> : <><div className="stats-table-scroll"><table className="stats-table stats-calls-table"><thead><tr><th>Date & heure</th><th>Interlocuteur</th><th>Sens</th><th>Utilisateur</th><th>Résultat</th><th>Durée</th><th><span className="stats-sr">Détail</span></th></tr></thead><tbody>{sorted.slice(currentPage * 15, (currentPage + 1) * 15).map(call => <tr key={call.id}><td>{new Date(call.createdAt).toLocaleString("fr-FR", { timeZone: timezone, day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit" })}</td><td>{formatPhone(call.remoteNumber)}</td><td><span className="stats-direction">{call.direction === "inbound" ? <ArrowDownLeft size={15}/> : <ArrowUpRight size={15}/>} {call.direction === "inbound" ? "Entrant" : "Sortant"}</span></td><td>{userNames(call)}</td><td><span className={`stats-result ${outcome(call)}`}>{OUTCOMES[outcome(call)]}</span></td><td>{duration(call.durationSeconds)}</td><td><button className="text-button" onClick={() => setSelected(call)} aria-label={`Détail de l’appel ${call.remoteNumber}`}>Détail</button></td></tr>)}</tbody></table></div><div className="stats-pagination"><span>{currentPage * 15 + 1}–{Math.min((currentPage + 1) * 15, calls.length)} sur {number(calls.length)}</span><div><button disabled={currentPage === 0} onClick={() => setPage(currentPage - 1)}>Précédent</button><span>{currentPage + 1} / {pages}</span><button disabled={currentPage >= pages - 1} onClick={() => setPage(currentPage + 1)}>Suivant</button></div></div></>}{selected && <Modal title="Détail de l’appel" onClose={() => setSelected(null)}><dl className="stats-call-detail">{Object.entries({ "Interlocuteur": formatPhone(selected.remoteNumber), "Date": new Date(selected.createdAt).toLocaleString("fr-FR", { timeZone: timezone }), "Fuseau": timezone, "Ligne": formatPhone(data.lines.find(line => line.id === selected.lineId)?.number ?? selected.lineId), "Utilisateur": userNames(selected), "Sens": selected.direction === "inbound" ? "Entrant" : "Sortant", "Résultat": OUTCOMES[outcome(selected)], "Durée mesurée": duration(selected.durationSeconds), "Parcours": selected.routing === "direct" ? "Direct" : selected.routing === "ivr" ? "IVR classique" : "Parcours avancé", "Messages vocaux": selected.voicemailCount, "Demandes de transfert": selected.transfers }).map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl></Modal>}</section>;
}
function VoiceStatistics({ calls }: { calls: TimedCall[] }) {
  const routed = calls.filter(call => call.routing !== "direct"), stats = summarize(routed), all = summarize(calls);
  return <><div className="stats-voice-intro"><div className="stats-voice-icon"><GitBranch size={26}/></div><div><h3>Du premier accueil à la bonne personne.</h3><p>Suivez vos parcours vocaux et les messages laissés après l’appel.</p></div><span className="stats-stage">Mesures disponibles</span></div><div className="stats-kpis stats-voice-kpis"><Kpi label="Appels avec parcours vocal" value={number(stats.total)} current={stats.total} note="IVR classique et parcours avancés" icon={<GitBranch/>}/><Kpi label="Connexion après routage" value={percentage(stats.connectionRate)} current={stats.connectionRate} note={`${stats.connected} connexions confirmées`} icon={<CheckCircle/>}/><Kpi label="Messages vocaux déposés" value={number(all.voicemailCount)} current={all.voicemailCount} note={`Durée moyenne : ${duration(all.voicemailCount ? all.voicemailSeconds / all.voicemailCount : null)}`} icon={<Voicemail/>}/><Kpi label="Demandes de transfert" value={number(stats.transfers)} current={stats.transfers} note="Demandes enregistrées dans le parcours" icon={<ArrowUpRight/>}/></div><p className="stats-note"><Info size={17}/>Les parcours avancés peuvent router directement sans menu. Les événements de branche, d’attente et d’écoute ne sont pas encore conservés ; ces indicateurs ne sont donc pas calculés.</p></>;
}
